### ISSUE TITLE
Start/Stop timer bug

### ISSUE THREAD

**Issue by monomadic** [caarlos0/tasktimer#33]
Hi, great little app, and seems like exactly what I need, but it currently has a strange UX quirk (possibly a bug) when starting/stopping tasks. Hitting enter on a task does not start/stop the task, it re-focuses the input for adding a new task. Also hitting enter on the input when it is empty moves the 'selected task' highlight to the top of the list.

Very strange behavior, I looked through the code and it appears intentional. The instructions in the interface directly contradict the actual behavior and I still can't find a way to 'resume' tasks.

Is this intended?

**Comment by caarlos0** [comment]
hey! 

there is no "resume tasks", you just create new tasks - task descriptions may repeat

**Comment by graugans** [comment]
I was also struggling with this behaviour. Could not find any hint in the README.
